#ifndef VIETTELSDK_COMMAND_LIST_H_
#define VIETTELSDK_COMMAND_LIST_H_

#ifndef POWER_OFF
#define POWER_OFF "AT+CPOWD"
#endif

#ifndef EPS_NETWORK_REGISTRATION_STATUS
#define EPS_NETWORK_REGISTRATION_STATUS "AT+CEREG"
#endif

#ifndef SHOW_ICCID
#define SHOW_ICCID "AT+CICCID"
#endif

#ifndef SIGNAL_QUALITY_REPORT
#define SIGNAL_QUALITY_REPORT "AT+CSQ"
#endif

#ifndef COMMAND_ECHO_MODE
#define COMMAND_ECHO_MODE "ATE"
#endif

#ifndef COMMAND_LED_MODE
#define COMMAND_LED_MODE "AT+QCLEDMODE"
#endif

#ifndef REQUEST_IMEI
#define REQUEST_IMEI "AT+CGSN"
#endif

#ifndef REQUEST_TA_REVISION_ID
#define REQUEST_TA_REVISION_ID "AT+CGMR"
#endif

#ifndef OPERATOR_SELECTION
#define OPERATOR_SELECTION "AT+COPS"
#endif

#ifndef REPORT_MOBILE_EQUIPMENT_ERROR
#define REPORT_MOBILE_EQUIPMENT_ERROR "AT+CMEE"
#endif

#ifndef DISPLAY_PRODUCT_ID
#define DISPLAY_PRODUCT_ID "ATI"
#endif

#ifndef REQUEST_MANUFACTURER_ID
#define REQUEST_MANUFACTURER_ID "AT+CGMI"
#endif

#ifndef REQUEST_MODEL_ID
#define REQUEST_MODEL_ID "AT+CGMM"
#endif

#ifndef REQUEST_INTERNATIONAL_MOBILE_SUBSCRIBER_IDENTITY
#define REQUEST_INTERNATIONAL_MOBILE_SUBSCRIBER_IDENTITY "AT+CIMI"
#endif

#ifndef GET_AND_SET_MOBILE_OPERATION_BAND
#define GET_AND_SET_MOBILE_OPERATION_BAND "AT+QCBAND"
#endif

#ifndef SET_DEFAULT_PSD_CONNECTION
#define SET_DEFAULT_PSD_CONNECTION "AT+QCATTBEARER"
#endif

#ifndef RETURNS_SOME_KEY_PARAMETER_IN_UE_SIDE
#define RETURNS_SOME_KEY_PARAMETER_IN_UE_SIDE "AT+QCSTATUS"
#endif

#ifndef PREFERRED_OPERATOR_LIST
#define PREFERRED_OPERATOR_LIST "AT+CPOL"
#endif

#ifndef SET_PMU_MODE
#define SET_PMU_MODE "AT+QCPMUCFG"
#endif

#ifndef SET_BAUDRATE_AT_CMD
#define SET_BAUDRATE_AT_CMD "AT+IPR"
#endif

#ifndef ENABLE_RELEASE_ASSISTANCE_INDICATION_AT_CMD
#define ENABLE_RELEASE_ASSISTANCE_INDICATION_AT_CMD "AT+CNBIOTRAI"
#endif

#ifndef CONFIG_CIOT_OPTIMIZATION_AT_CMD
#define CONFIG_CIOT_OPTIMIZATION_AT_CMD "AT+CCIOTOPT"
#endif

#ifndef CONFIG_SLOW_CLOCK_AT_CMD
#define CONFIG_SLOW_CLOCK_AT_CMD "AT+CSCLK"
#endif

#ifndef CONFIG_SOCKET_RETENTION_AT_CMD
#define CONFIG_SOCKET_RETENTION_AT_CMD "AT+RETENTION"
#endif

#ifndef PSM_AT_CMD
#define PSM_AT_CMD "AT+CPSMS"
#endif

#ifndef CONFIG_EDRX_AT_CMD
#define CONFIG_EDRX_AT_CMD "AT*MEDRXCFG"
#endif

#ifndef QUERY_EDRX_AT_CMD
#define QUERY_EDRX_AT_CMD "AT+CEDRXRDP"
#endif

#ifndef ENTER_PIN
#define ENTER_PIN "AT+CPIN"
#endif

#ifndef PHONE_FUCNTIONALITY
#define PHONE_FUCNTIONALITY "AT+CFUN"
#endif

#ifndef READ_DYNAMIC_PARAM_PDP_CONTEXT
#define READ_DYNAMIC_PARAM_PDP_CONTEXT "AT+CGCONTRDP"
#endif

#ifndef AUTO_TIME_UPDATE
#define AUTO_TIME_UPDATE "AT+CTZU"
#endif

#ifndef ENABLE_LOCAL_TIMESTAMP
#define ENABLE_LOCAL_TIMESTAMP "AT+CLTS"
#endif

#ifndef GET_CLOCK
#define GET_CLOCK "AT+CCLK"
#endif

#ifndef CHECK_ACTIVE_PDP_CONTEXT
#define CHECK_ACTIVE_PDP_CONTEXT "AT+CGACT"
#endif

#ifndef REPORT_THE_POWER_SAVING_MODE_STATUS
#define REPORT_THE_POWER_SAVING_MODE_STATUS "AT+QCPSMR"
#endif

/* MQTT */
#ifndef CREATE_NEW_MQTT_AT_CMD
#define CREATE_NEW_MQTT_AT_CMD "AT+CMQNEW"
#endif

#ifndef SEND_NEW_MQTT_CONNECTION_PACKET_AT_CMD
#define SEND_NEW_MQTT_CONNECTION_PACKET_AT_CMD "AT+CMQCON"
#endif

#ifndef SEND_MQTT_PUBLISH_PACKET_AT_CMD
#define SEND_MQTT_PUBLISH_PACKET_AT_CMD "AT+CMQPUB"
#endif

#ifndef DISCONNECT_MQTT_AT_CMD
#define DISCONNECT_MQTT_AT_CMD "AT+CMQDISCON"
#endif

#ifndef RELEASE_MQTT_CLIENT
#define RELEASE_MQTT_CLIENT "AT+CMQTTREL"
#endif

#ifndef START_MQTT_SERVICE
#define START_MQTT_SERVICE "AT+CMQTTSTART"
#endif

#ifndef ACQUIRE_MQTT_CLIENT
#define ACQUIRE_MQTT_CLIENT "AT+CMQTTACCQ"
#endif

#ifndef CONNECT_TO_MQTT_SERVER
#define CONNECT_TO_MQTT_SERVER "AT+CMQTTCONNECT"
#endif

#ifndef PUBLISH_A_MESSAGE_TO_SERVER
#define PUBLISH_A_MESSAGE_TO_SERVER "AT+CMQTTPUB"
#endif

#ifndef SUBCRIBE_MQTT_MESSAGE_TO_SERVER
#define SUBCRIBE_MQTT_MESSAGE_TO_SERVER "AT+CMQTTSUB"
#endif

#ifndef INPUT_THE_TOPIC_OF_PUBLISH_MESSAGE
#define INPUT_THE_TOPIC_OF_PUBLISH_MESSAGE "AT+CMQTTTOPIC"
#endif

#ifndef INPUT_THE_PUBLISH_MESSAGE
#define INPUT_THE_PUBLISH_MESSAGE "AT+CMQTTPAYLOAD"
#endif

#ifndef SEND_MQTT_UNSUB
#define SEND_MQTT_UNSUB "AT+CMQUNSUB"
#endif

#ifndef DISCONNECT_MQTT
#define DISCONNECT_MQTT "AT+CMQTTDISC"
#endif

#ifndef STOP_MQTT_SERVICE
#define STOP_MQTT_SERVICE "AT+CMQTTSTOP"
#endif

/* AT+QCBAND */
typedef enum AT_QCBAND {
	EGSM_MODE = 0, DCS_MODE, ALL_MODE
} AT_QCBAND;

#endif /* VIETTELSDK_COMMAND_LIST_H_ */
